### ISSUE TITLE
Hydration when using fetch on client side breaks the nuxt site

### ISSUE THREAD

**Issue by xaander1** [harlan-zw/nuxt-delay-hydration#4]
The module seem to prevent the app from executing fetch api calls on client side. 

Here is a reproduction of the issue: 

https://codesandbox.io/s/nuxt-delay-hydrate-fetch-api-bug-ucd2o

@harlan-zw advise on such a scenario

**Comment by harlan-zw** [comment]
Not sure what exactly is going on here, seems like the issue is that you don't have the module in manual mode but you are using it as if it was in manual mode.

Using the latest version and setting to manual mode seems to have the fetch work correctly. The component should be automatically imported for you via nuxt/components 

```
 delayHydration: {
    mode: "manual"
  }
```

If you still have issues let me know
